### ISSUE TITLE
Draft the Developer Guide (DG)

### ISSUE THREAD

**Issue by limerencee** [AY1920S1-CS2103T-W12-2/main#42]
1. Update Developer Guide (DG) to include our application details:
    a. Target user profile, value proposition and user stories.
    b. Use cases.
    c. NFR: performance requirements, usability requirements, scalability requirements, etc.
    d. Glossary

**Comment by limerencee** [comment]
This can be marked as done with commit 7d8fc36 merged, unless anyone else has other matters to add? 😁

**Comment by lightz96** [comment]
Use cases are not completed yet.
