### ISSUE TITLE
Lye Jian Wen: Update Transaction command

### ISSUE THREAD

**Issue by lye-jw** [AY1920S1-CS2103T-W12-2/main#57]
v1.2: Update a Transaction with new details.

Resolves #95 #44 #12
Addresses #11, #31 

Also used to modify and manage planned transactions.

**Comment by lye-jw** [comment]
Increments:
1. #88 
2. #98 
3. #109 
4. #121

**Comment by limerencee** [comment]
How would `update` address #11 and #31?

**Comment by lye-jw** [comment]
> How would `update` address #11 and #31?

Apologies, it doesn't yet but will for updating Planned Transactions and budget. It only indirectly addresses them, while #95, #44 and #12 will be resolved

**Comment by lye-jw** [comment]
Closed with #113
